link:
  railstutorial:
    home: "https://www.railstutorial.org/"
    help: "https://www.railstutorial.org/help"
    book: "https://www.railstutorial.org/book"
    screencasts: "https://screencasts.railstutorial.org/"
    contact: "https://www.railstutorial.org/contact"
  learnenough:
    home: "https://www.learnenough.com/"
  michaelhartl:
    home: "https://www.michaelhartl.com/"
  gravatar:
    emails: "https://gravatar.com/emails"
rails:
  img: "rails.svg"
  alt: "Rails logo"
  width: "200px"
  link: "https://rubyonrails.org/"
validation:
  user:
    name:
      max_length: 50
    email:
      valid_email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
      max_length: 255
    password:
      min_length: 6
avatar_size: 80
avatar_small_size: 50
avatar_tiny_size: 30
checkbox: "1"
pagination: 10
password_reset_expired: 2
micropost:
  format:
    - image/jpeg 
    - image/gif 
    - image/png
  max_length: 140
  pagination: 10
  image:
    size: 5
    resize_to_limit:
      - 500
      - 500
  types: "image/jpeg,image/gif,image/png"
